
# Spring Datasource Configuration for H2
spring:
  application:
    name: coding-practice

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



# Server Configuration
server:
  port: 9091
  servlet:
    context-path: /api/v1


